stages:
  data_ingestion:
    cmd: python src/textclassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/textclassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/train.csv


  prepare_base_model:
    cmd: python src/textclassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/textclassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - root_dir
      - model_path
      - params_learning_rate
      - params_epoch
      - params_batch_size
      - params_vocab
      - params_sent_length
      - params_sen_length
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/textclassifier/pipeline/stage_03_model_training.py
    deps:
      - src/textclassifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/train.csv
      - artifacts/prepare_base_model
    params:
      - root_dir
      - base_model_path
      - trained_model_path
      - training_data
      - params_is_epochs
      - params_is_batch_size
      - params_is_vocab
      - params_is_sent_length
      - params_is_sen_length
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/textclassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/textclassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false